{% set name = "pcicrawler" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e6c12b10e4adc9271f7331da4b673d0cb9a6c9e48bba00cd5b7954ada1690a5

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - pcicrawler
  commands:
    - pcicrawler --help

about:
  home: https://github.com/facebook/pcicrawler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pcicrawler is a CLI tool to display/filter/export information about PCI or PCI Express devices and their topology.

extra:
  recipe-maintainers:
    - hmaarrfk
